language: go
sudo: required
go:
  - 1.11.1
services:
  - docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=akolk/oracledb_exporter
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64 
install: true
script: make travis
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./docker_push
  file:
    - "./dist/oracledb_exporter.linux-amd64"
    - "./dist/oracledb_exporter.darwin-amd64"
  on:
    branch: master

#after_success:
#  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
#  - docker push $REPO:latest
