[[metric]]
context = "context_no_label"
request = "select count(*) as value_1 from v$transactions where status='ACTIVE'"
metricsdesc = { value_1 = "Number of active transactions." }

[[metric]]
context = "context_no_label"
request = "select count(*) as value_1 from v$transactions where status='ACTIVE'"
metricsdesc = { value_1 = "Number of active transactions." }

[[metric]]
context = "context_with_labels"
labels = [ "label_1", "label_2" ]
request = "SELECT 1 as value_1, 2 as value_2, 'First label' as label_1, 'Second label' as label_2 FROM DUAL"
metricsdesc = { value_1 = "Simple example returning always 1.", value_2 = "Same but returning always 2." }
